-- Auto-generated by Matugen
return {
  { "nvim-treesitter", enabled = false }, {
  "nvim-mini/mini.base16",
  config = function()
    require('mini.base16').setup({
      palette = {
        base00 = '{{colors.background.default.hex}}',
        base01 = '{{colors.surface_container_lowest.default.hex}}',
        base02 = '{{colors.surface_container_low.default.hex}}',
        base03 = '{{colors.outline_variant.default.hex}}',
        base04 = '{{colors.on_surface_variant.default.hex}}',
        base05 = '{{colors.on_surface.default.hex}}',
        base06 = '{{colors.inverse_on_surface.default.hex}}',
        base07 = '{{colors.surface_bright.default.hex}}',
        base08 = '{{colors.on_surface.default.hex | set_lightness: 80.0 }}',
        base09 = '{{colors.secondary.default.hex}}',
        base0A = '{{colors.tertiary.default.hex}}',
        base0B = '{{colors.primary.default.hex}}',
        base0C = '{{colors.secondary.default.hex}}',
        base0D = '{{colors.primary_container.default.hex}}',
        base0E = '{{colors.secondary_container.default.hex}}',
        base0F = '{{colors.error.default.hex}}',
      }
    })


    -- We first theme base16, but we also need to fix some other colors that don't
    -- contrast well by default

    -- Helper function to set multiple highlight groups at once
    local function set_hl_mutliple(groups, value)
      for _, v in pairs(groups) do
        vim.api.nvim_set_hl(0, v, value)
      end
    end

    -- Make selected text stand out more
    vim.api.nvim_set_hl(0, 'Visual', {
      bg = '{{colors.surface.default.hex | set_lightness: 30}}',
      fg = '{{colors.surface.default.hex | set_lightness: 80}}',
    })

    set_hl_mutliple({ 'TSComment', 'Comment' }, {
      fg = '{{colors.on_surface.default.hex | set_lightness: 30}}',
    })

    set_hl_mutliple({ 'TSMethod', 'Method' }, {
      fg = '{{colors.tertiary.default.hex}}',
    })

    set_hl_mutliple({ 'TSFunction', 'Function' }, {
      fg = '{{colors.tertiary_fixed.default.hex}}',
    })

    vim.api.nvim_set_hl(0, 'Keyword', {
      fg = '{{colors.primary.default.hex}}',
    })

    vim.api.nvim_set_hl(0, 'MsgArea', {
      bg = '{{colors.surface_container_lowest.default.hex}}',
      fg = '{{colors.primary.default.hex}}',
    })

    -- An example subset of your init.lua

    local function source_matugen()
      -- Update this with the location of your output file
      local matugen_path = os.getenv("HOME") .. "/.config/nvim/matugen.lua" -- dofile doesn't expand $HOME or ~

      local file, err = io.open(matugen_path, "r")
      -- If the matugen file does not exist (yet or at all), we must initialize a color scheme ourselves
      if err ~= nil then
        -- Some placeholder theme, this will be overwritten once matugen kicks in
        vim.cmd('colorscheme base16-catppuccin-mocha')

        -- Optionally print something to the user
        vim.print(
          "A matugen style file was not found, but that's okay! The colorscheme will dynamically change if matugen runs!")
      else
        dofile(matugen_path)
        io.close(file)
      end
    end

    -- Main entrypoint on matugen reloads
    local function auxiliary_function()
      -- Load the matugen style file to get all the new colors
      local matugen_path = os.getenv("HOME") .. "/.config/nvim/generated.lua"
      source_matugen()

      -- Because reloading base16 overwrites lualine configuration, just source lualine here
      dofile(os.getenv("HOME") .. '/.config/nvim/config/plugins/lualine-nvim.lua') -- path of your lualine setup

      -- Any other options you wish to set upon matugen reloads can also go here!
      vim.api.nvim_set_hl(0, "Comment", { italic = true })
    end

    -- Register an autocmd to listen for matugen updates
    vim.api.nvim_create_autocmd("Signal", {
      pattern = "SIGUSR1",
      callback = auxiliary_function,
    })

    -- Additionally call this function once on startup to query for matugen's theme
    -- or set a default
    auxiliary_function()
  end
} }
